kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "vsphere-sdk" 
  namespace: open-cluster-management
spec:
  output:
    to:
      kind: DockerImage
      name: 'quay.io/fdavalo/vsphere-sdk:v1'
    pushSecret:
      name: fdavalo-fdavalo-robot-pull-secret
  strategy:
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers  
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/fdavalo/mce-agent-provision-vms'
      ref: 'main'
    contextDir: 'src'
    dockerfile: "FROM image-registry.openshift-image-registry.svc:5000/openshift/python:3.8\nRUN pip3 install --upgrade git+https://github.com/vmware/vsphere-automation-sdk-python.git\nCOPY vm-delete.py ."
  runPolicy: Serial
