apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: download-infraenv-iso
  namespace: hcp-config
rules:
  - apiGroups:
      - 'agent-install.openshift.io'
    resources:
      - infraenvs
      - agents
    verbs:
      - get
      - list
      - patch
      - update
      - delete
