apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-agents-baremetal
  namespace: baremetal
rules:
  - apiGroups:
      - 'agent-install.openshift.io'
    resources:
      - agents
    verbs:
      - get
      - list
      - patch
      - update
      - delete
