apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-infraenv-iso
  namespace: baremetal
rules:
  - apiGroups:
      - 'agent-install.openshift.io'
    resources:
      - infraenvs
    verbs:
      - get
      - list
      - patch
      - update
      - delete
