kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: download-infraenv-iso
  namespace: hcp-config
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: hpe-redhat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: download-infraenv-iso
